### ISSUE TITLE
Running on GPU using CuArray

### ISSUE THREAD

**Issue by lukehutch** [KristofferC/NearestNeighbors.jl#104]
I'm new to Julia, and I'm trying it out because it seems to be the simplest way to program GPUs right now using `CuArray`. I need a fast kd-tree algorithm that runs on a GPU, among other things, and I found `NearestNeighbors.jl`. How much work would be involved in getting this code working out of `CuArray` instances rather than its current CPU-bound data structures?

**Comment by KristofferC** [comment]
My guess is quite a lot of work is needed but I have no experience with KD trees on GPUs so I might be wrong.

**Comment by lukehutch** [comment]
This post might be helpful:

https://nextjournal.com/sdanisch/julia-gpu-programming

**Comment by KristofferC** [comment]
Don't see a reason to keep this open since there isn't really any actionable here.
