### ISSUE TITLE
Suggestion: Make KDTree interruptible 

### ISSUE THREAD

**Issue by colemanbroad** [KristofferC/NearestNeighbors.jl#113]
In the REPL, I naively tried to build a `KDTree` on a 10_000x5 (NxP) array of points before realizing the implicit order should have been (PxN). The function did not return and was even unresponsive to holding `Ctrl-C`. I believe checking for such interrupt signals is the responsibility of the library, not the REPL? I believe this is likely to be a common beginners mistake, and thus it may make sense to check more frequently for interrupts?

I otherwise love the package. Simple interface, highly generic and blazing fast ;)
Thank you.

**Comment by KristofferC** [comment]
> I believe checking for such interrupt signals is the responsibility of the library, not the REPL

It is not. Julia itself checks the signal and throws an interrupt exception. However, there are only some places where this is possible. If you try to interrupt in a place where this isn't the case, it won't exit gracefully. There is nothing the package can do about that.
