### ISSUE TITLE
BruteTree with other metrics than Euclidean()

### ISSUE THREAD

**Issue by mlesnoff** [KristofferC/NearestNeighbors.jl#122]
Hello
From the doc: "BruteTree: ... Works with any Metric." "This is one of the Metric types defined in the Distances.jl packages."

I was tryiing to use BruteTree with other metrics of Distances.jl than Euclidean(), but without success

#### This works
BruteTree(rand(5, 3), Euclidean())

#### But not this
BruteTree(rand(5, 3), CosineDist())
BruteTree(rand(5, 3), CorrDist())

I just saw that they were semi-metrics, not pure metrics, but the doc says "one of the Metric types defined in the Distances.jl packages". Did I undetsand something wrong?

And is there a specific way to use BruteTree and knn with CosineDist() or CorrDist()?

By the way, 
BruteTree(rand(5, 3), SqEuclidean())
seems not working neither

Thanks in advance

**Comment by KristofferC** [comment]
Dup of https://github.com/KristofferC/NearestNeighbors.jl/issues/99.
