### ISSUE TITLE
Nearest Neighbors in a very large dataset.

### ISSUE THREAD

**Issue by compleathorseplayer** [KristofferC/NearestNeighbors.jl#140]
Pardon me if this is a stupid question (or covered under another heading which I did not see), but is there a version here (or a way of using) that works for relatively large (~250k points of 20 dims) dataset?   KDTree freezes my machine at this scale.  I tried increasing the leafsize, but it didn't help and anyway, I don't have a feel for how to sensibly adjust.

I would be grateful for any suggestions.

Thanks in advance!
PS I am really mainly interested in Regression/Classification
PPS  Apologies - I have tried so many methods - each with different calling sequence - I had transposed the matrix :-b     Works OK the right way round

**Comment by KristofferC** [comment]
My guess is you mixed up dimensions and number of points?
