### ISSUE TITLE
BallTree and KDTree do not accept Vector{AbstractVector{Float64}} Type. Possible bug.

### ISSUE THREAD

**Issue by samadritakarmakar** [KristofferC/NearestNeighbors.jl#144]
Hi!

There seems to be a bug in /src/tree_data.jl:14
`MethodError: no method matching length(::Type{AbstractVector{Float64}})`

Way to reproduce the bug:

    points = rand(3, 60);
    newPoints = Vector{AbstractVector{Float64}}(undef, size(points, 2));
    for i ∈ 1:length(newPoints)
         newPoints[i] = @view points[:, i]
    end
    BallTree(newPoints)

I suggest changing the given line:
`n_dim, n_p = length(V), length(data)`
to 
`n_dim, n_p = length(data[1]), length(data)`

Since all points must have the same dimension, it should be sufficient to assume that the first vector is a good reference.

also the same kind of bug is also likely present in src/kd_tree.jl:36 and src/ball_tree.jl:40

**Comment by KristofferC** [comment]
Dup of https://github.com/KristofferC/NearestNeighbors.jl/issues/121
