### ISSUE TITLE
BallTree only works with any Distances.UnionMetrics

### ISSUE THREAD

**Issue by schmrlng** [KristofferC/NearestNeighbors.jl#18]
The BallTree implementation relies on the column-selecting evaluation methods in https://github.com/KristofferC/NearestNeighbors.jl/blob/master/src/evaluation.jl which only work for metrics that can be expressed as element-wise reductions (i.e. Distances.UnionMetrics). Does the underlying math of the BallTree truly apply to any Metric (or SemiMetric)? If that is the case, a fallback implementation relying on ```slice``` would be nice so that the weighted metrics and user-defined metrics can be used.

**Comment by KristofferC** [comment]
Such a fallback would definitely be good to have. I'm on vacation so it will take a while for me to get to this but I could probably review a PR quite fast.
