### ISSUE TITLE
RFH: 0.5-style comprehensions broke the way you're using testsets

### ISSUE THREAD

**Issue by tkelman** [KristofferC/NearestNeighbors.jl#25]
You might be using `@testset for` in a more complicated way than most other people? I think there's a base Julia bug here, but I could use a hand in reducing the test case from here. See http://pkg.julialang.org/detail/NearestNeighbors.html
```
Test Summary: | Pass  Total
  inrange     |   24     24
ERROR: LoadError: LoadError: syntax: break or continue outside loop
 in include_from_node1(::String) at ./loading.jl:426 (repeats 2 times)
 in process_options(::Base.JLOptions) at ./client.jl:266
 in _start() at ./client.jl:322
while loading /home/vagrant/.julia/v0.5/NearestNeighbors/test/test_monkey.jl, in expression starting on line 6
while loading /home/vagrant/.julia/v0.5/NearestNeighbors/test/runtests.jl, in expression starting on line 34
```

I bisected the failure to Julia commit https://github.com/JuliaLang/julia/commit/cd35df536bd, and I'm pretty sure this is an unintended consequence. Base apparently needs more tests of nested testsets with break/continue in them.

**Comment by KristofferC** [comment]
Interesting. I am at Denver airport right now but will try to make a reduced example in a couple of days when I am home.

**Comment by tkelman** [comment]
hope you had a good trip

**Comment by KristofferC** [comment]
Was really awesome. Las Vegas -> Zion National Park -> Antelope Canyon -> Grand Canyon -> Monument Valley -> Arches National Park -> Aspen. Now fly to Washington DC and then home.

So much pretty stuff here.. Really amazing.

**Comment by tkelman** [comment]
maybe related to https://github.com/JuliaLang/julia/issues/17170

**Comment by KristofferC** [comment]
Fixed now

**Comment by tkelman** [comment]
possibly about to break again ref https://github.com/JuliaLang/julia/pull/17389#issuecomment-237168170, didn't check the log in detail yet though
