### ISSUE TITLE
using KDtree as a type?

### ISSUE THREAD

**Issue by lobingera** [KristofferC/NearestNeighbors.jl#32]
I've just seen the error the first time, i used (some time ago...) KDTree in a type definition

```
type pgraph
    x_screen::Array{Float64,1}
    y_screen::Array{Float64,1}
    x_last::Real
    y_last::Real
    kdtree::NearestNeighbors.KDTree{Float64,Distances.Euclidean}
end
```

which is later on instantiated with
```
p1 = pgraph(x,y,0.0,0.0,KDTree(zeros(2,2));
```

and p1.kdtree then given a value when applicable.

How to do that now?

**Comment by lobingera** [comment]
Don't mind, i'm using ::Any right now.

**Comment by KristofferC** [comment]
You could have 
```jl
type pgraph{T <: KDTree}
kdtree::T
```

**Comment by lobingera** [comment]
This was just an example, pgraph is actually a little bit longer than this and i might reserve the "top-level type argument" (don't know how {T <: X} is called...) for data, not the KDTree representation. The initial example worked for some time...

**Comment by KristofferC** [comment]
Yes, The new version (#29) changes the way the KDTree is parameterized. It is now a sufficiently complex type that I would recommand just adding an extra parameter that is `T <: KDTree` to your type.
