### ISSUE TITLE
 [Breaking] MethodError: no method matching length(::Type{Array{Float64,1}})

### ISSUE THREAD

**Issue by Datseris** [KristofferC/NearestNeighbors.jl#54]
After my latest update I do:

```julia
NearestNeighbors
a = [rand(3) for i in 1:100]
KDTree(a)

MethodError: no method matching length(::Type{Array{Float64,1}})
Closest candidates are:
  length(!Matched::SimpleVector) at essentials.jl:256
  length(!Matched::Base.MethodList) at reflection.jl:558
  length(!Matched::MethodTable) at reflection.jl:634
  ...
in NearestNeighbors.KDTree at NearestNeighbors\src\kd_tree.jl:34
in #KDTree#12 at NearestNeighbors\src\kd_tree.jl:36
in NearestNeighbors.TreeData at NearestNeighbors\src\tree_data.jl:14
```

**Comment by KristofferC** [comment]
Docs are pretty clear:

> Vector{V} where V is itself a subtype of an AbstractVector and such that eltype(V) and length(V) is defined.

So you need to use either `rand(3, 100)` or something like `[rand(SVector{3} for i in 1:100]` using StaticArrays. Your version would have very bad performance.

**Comment by Datseris** [comment]
I am sorry, I did not see that. It must be new right? (Because previously it worked for me...)

**Comment by KristofferC** [comment]
Been there since https://github.com/KristofferC/NearestNeighbors.jl/pull/29

**Comment by Datseris** [comment]
Thanks. It seems that I have actually never used it with `Vector{Vector}`, only with `Vector{SVector}`...

Since many times I have data that are `Vector{Vector}`, do you know of a good way to make them passable to KDTree? I am trying `reinterpret(SVector,...)` but can't make it work.

**Comment by KristofferC** [comment]
You can't reinterpret because the memory layout is different.
