### ISSUE TITLE
Trees for non-Metrics?

### ISSUE THREAD

**Issue by oxinabox** [KristofferC/NearestNeighbors.jl#75]
For NLP it is common to want to use `CosineDist`,
which is a `SemiMetric`.

This is not going to be compatible with the BallTree, I think.

but it should be fine with the `BruteTree`.

**Comment by davidbp** [comment]
This would come in handy for `Clustering.jl`,  what do you think @KristofferC ? Currently cluster assigment is performed computing and storing all pairwise distances, which is quite bad memory wise.

**Comment by KristofferC** [comment]
`BruteTree` is more or less "useless" and is only there to basically check results vs the other trees. I think this is a bit out of scope of the package.
