### ISSUE TITLE
Interpret 1-dimensional array as 1 point

### ISSUE THREAD

**Issue by BioTurboNick** [KristofferC/NearestNeighbors.jl#76]
I have code that makes 3xN arrays as input to BallTree. However, when there is only one point, it produces a 3-member 1-dimensional array.

When this 1-dimensional array is input to the Tree constructors, I get the error `MethodError: no method matching KDTree(::Array{Float64,1})`.

I believe the package would be more robust if the Tree constructor accepted 1-dimensional arrays and interpreted it as a single point.

Workaround:  Use reshape to enforce 2-dimensionality

**Comment by KristofferC** [comment]
Closed in https://github.com/KristofferC/NearestNeighbors.jl/pull/77.

Re-looking over this, I still find this to be kinda bad. A one dimensional vector or a matrix with one column are fundamentally different things and shouldn't be mixed like this. Oh well.

**Comment by BioTurboNick** [comment]
Fair enough! :-)

**Comment by Moelf** [comment]
for a user case where data points are just 1D, can a user still use this package?

I'm talking about use case like:
```julia-repl
julia> using Chairmarks

julia> a = sort(rand(10^7)); b = sort(rand(10^7));

julia> function f(a,b)
           for x in a
               searchsortedfirst(b, x)
           end
       end
f (generic function with 1 method)

julia> @be f($a,$b)
Benchmark: 3284 samples with 1754 evaluations
min    15.290 ns
median 15.970 ns
mean   16.221 ns
max    27.908 ns
```

obviously replacing `searchsotredfirst` with a NN search
