### ISSUE TITLE
Is there any plan to introduce  una-dinosauria/Rayuela.jl ??

### ISSUE THREAD

**Issue by zsz00** [KristofferC/NearestNeighbors.jl#91]
Is there any plan to introduce  una-dinosauria/Rayuela.jl ??

https://github.com/una-dinosauria/Rayuela.jl
Rayuela.jl is a package that implements non-orthogonal multi-codebook quantization methods (MCQ). These methods are useful for fast search of high-dimensional (d=100s-1000s) dense vectors. Rayuela is written in Julia.

**Comment by zgornel** [comment]
You can check [IVFADC.jl](https://github.com/JuliaNeighbors/IVFADC.jl) for nearest neighbor search using vector quantization
