### ISSUE TITLE
Weird behaviour with Periodic Euclidean metric

### ISSUE THREAD

**Issue by natschil** [KristofferC/NearestNeighbors.jl#96]
I'm somewhat confused by the following (non-working) example:
```
using Distances,NearestNeighbors
pred = Distances.PeriodicEuclidean([Inf,2.5])
l = [0.0 0.0; 0.0 2.5]
S = NearestNeighbors.BallTree(l,pred)
println(inrange(S,[0.0,0.0],1e-2,true))
println(pred(l[:,1],l[:,2]))
```
This code prints [1] and then 0.0. I'm surprised because I would have expected the first println() to print [1,2] instead.  As far as I remember, this kind of code worked fine before; I'm unfortunately unable to isolate a commit that changed things.

**Comment by KristofferC** [comment]
Thanks for the report. Should be fixed by https://github.com/KristofferC/NearestNeighbors.jl/pull/97
